set relativenumber " SETAR OS NÚMEROS RELATIVOS.
set hidden " PERMITE ANDAR POR OUTROS ARQUIVOS MESMO TENDO ALGUM ARQUIVO NÃO SALVO.
set shiftwidth=4 " TAMANHO DO TAB EM ESPAÇOS
set tabstop=4 " TAMANHO DE TAB QUE DEVE SER USADO PARA RENDERIZAR ARQUIVOS
syntax enable " HABILITA O HIGHTLIGHT DO NEOVIM
set mouse=a " HABILITA SUPORTE AO MOUSE
set linebreak " FAZ COM QUE NÃO TENHA PALAVRAS QUEBRADAS NAS LINHAS
set autochdir " FAZ COM QUE SEMPRE MUDE O DIRETÓRIO PARA ONDE O ARQUIVO QUE ESTÁ EDITANDO ESTÁ.
